version: '3.8'

services:
  server:
    container_name: server
    build: 
      context: ./server
    env_file:
      - ./server/.env
    volumes:
      - .:/server
      - .:/server/node_modules
    ports:
      - 5000:5000
    depends_on:
      - postgres
    restart: always

  client:
    container_name: client
    build: 
      context: ./client
    volumes:
      - .:/client
      - .:/client/node_modules
    ports:
      - 5173:5173
    stdin_open: true
    tty: true
  
  postgres:
    container_name: postgres
    image: postgres
    restart: on-failure
    env_file:
      - ./server/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: